var Language = {
    "district": "Districts",
    "StateCity": "States - Cities",
    "RecentArrivalCities": "Recent arrival cities",
    "RecentDepartureCities": "Recent departurecities",
    "benxeh1": "Bus station",
    "chonngay": "Select Date",
    "PleaseEnterDepartureCity": "Please enter departure city",
    "PleaseEnterArrivalCity": "Please enter arrival city",
    "ward": "Wards",
    "AirportSearch": "Airport",
    "popularPlace": "Popular Place",
    "PleaseselectaDeparture": "Please select the pick-up point.",
    "PleaseselectaDestination": "Please select the drop-off point.",
    "PleaseTypeDeparturePlace": "Please enter your desired pickup point.",
    "PleaseTypeDestinationPlace": "Please enter your desired drop-off point.",
    "chuachonghe": "Please select at least one seat.",
    "ThereWasAnErrorWhileBookingTickets": "There was an error while booking ticket. Please try again later. Thank you.",
    "phanhoicuakhachhang": "Customer feedback",
    "thankfeedback": "Thank for your feedback",
    "pleaseselectanoption": "Please select an option",
    "pleaseselectanoptionorenteroption": "Please select an option or enter option",
    "feedback": "Feedback",
    "RegisterInfomation": "Register",
    "Updating": "Updating",
    "person": "person",
    "NameOfEachPassengerDuplicated": "Name of each passenger must not duplicated.",
    "opp": "Departure",
    "edp": "Arrival",
    "chxeh1": "Bus",
    "Soldout": "Sold Out",
    "Call": "Call",
    "BusType": "Bus type",
    "SeatType": "Seat type",
    "giodi": "Departure Time",
    "PleaseSelect4SeatsInOneBooking": "Please select maximum {maxTotalSeats} seats in one booking.",
    "PleaseConfirmYourReview": "Please confirm your review. Thank you.",
    "DepartPlace": "From",
    "Destination": "To",
    "DepartDate": "Date of journey",
    "Today": "Today",
    "Tomorrow": "Tomorrow",
    "Notication": "Not Found This Page",
    "PleaseEnterValidAddress": "Please select city and district"
};