var Language = {
    "district": "Quận - Huyện",
    "StateCity": "Tỉnh - Thành Phố",
    "RecentArrivalCities": "Nơi thường đến",
    "RecentDepartureCities": "Nơi thường đi",
    "benxeh1": "Bến xe",
    "chonngay": "Chọn ngày",
    "PleaseEnterDepartureCity": "Quý khách chưa nhập Nơi đi",
    "PleaseEnterArrivalCity": "Vui lòng nhập nơi đến",
    "ward": "Phường - Xã",
    "AirportSearch": "Sân bay",
    "popularPlace": "Điểm dừng phổ biến",
    "PleaseselectaDeparture": "Quý khách vui lòng chọn điểm đi.",
    "PleaseselectaDestination": "Quý khách vui lòng chọn điểm đến.",
    "PleaseTypeDeparturePlace": "Vui lòng nhập địa chỉ điểm đón cụ thể trong khu vực.",
    "PleaseTypeDestinationPlace": "Vui lòng nhập địa chỉ điểm trả cụ thể trong khu vực.",
    "chuachonghe": "Quý khách vui lòng chọn ít nhất một chỗ ngồi.",
    "ThereWasAnErrorWhileBookingTickets": "Có lỗi xảy ra trong quá trình đặt vé. Xin quý khách vui lòng đặt lại chuyến khác.",
    "phanhoicuakhachhang": "Phản hồi của khách hàng",
    "thankfeedback": "Cám ơn bạn đã góp ý cho chúng tôi",
    "feedback": "Góp ý",
    "pleaseselectanoption": "Vui lòng chọn nội dung góp ý",
    "pleaseselectanoptionorenteroption": "Vui lòng chọn nội dung góp ý hoặc nhập nội dung góp ý",
    "RegisterInfomation": "Đăng ký thông tin",
    "Updating": "Đang cập nhật",
    "person": "người",
    "NameOfEachPassengerDuplicated": "Tên của mỗi hành khách phải khác nhau.",
    "opp": "Điểm đón",
    "edp": "Điểm trả",
    "chxeh1": "Hãng xe",
    "Call": "Liên hệ",
    "Soldout": "Hết vé",
    "BusType": "Loại xe",
    "SeatType": "Loại ghế",
    "giodi": "Giờ đi",
    "PleaseSelect4SeatsInOneBooking": "Quý khách chỉ được chọn tối đa {maxTotalSeats} ghế cho mỗi lần đặt. Mọi thắc mắc vui lòng liên hệ hotline VeXeRe.com 1900969681",
    "PleaseConfirmYourReview": "Vui lòng xác nhận đánh giá của bạn. Cảm ơn !",
    "DepartPlace": "Gõ vào nơi đi",
    "Destination": "Gõ vào nơi đến",
    "DepartDate": "Chọn ngày đi",
    "Today": "Hôm nay",
    "Tomorrow": "Ngày mai",
    "Search": "Tìm Vé Xe Rẻ",
    "Notication": "không tìm thấy Trang này",
    "PleaseEnterValidAddress": "Vui lòng chọn thành phố và quận huyện"
};